#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Webserver

# General
WEB_DOCUMENT_ROOT=/app/Web/
WEB_DOCUMENT_INDEX=index.php
CLI_SCRIPT=php /app/flow

# Flow general settings
FLOW_REWRITEURLS=1
FLOW_PATH_TEMPORARY_BASE=/opt/tmp

#######################################
# SSH settings
# SSH public key (without comment):
# -> ssh-rsa AAAAB3Nza....
#  Github public ssh keys:
# -> https://github.com/USERNAME.keys
SSH_AUTH_KEY=""

#######################################
# PostgreSQL settings
POSTGRES_USER=dev
POSTGRES_PASSWORD=dev
